# Generated by Django 4.2.28 on 2026-03-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='region',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Hide from search engines'),
        ),
        migrations.AddField(
            model_name='region',
            name='og_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='region',
            name='og_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='schema_json',
            field=models.JSONField(blank=True, help_text='Full JSON-LD structured data', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='schema_type',
            field=models.CharField(blank=True, choices=[('TouristAttraction', 'Tourist Attraction'), ('Article', 'Article'), ('Person', 'Person'), ('Organization', 'Organization')], max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='sitemap_changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='region',
            name='sitemap_priority',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2),
        ),
    ]
