# Generated by Django 4.2.28 on 2026-03-01 20:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_type', models.CharField(choices=[('polygon', 'Polygon'), ('circle', 'Circle'), ('corridor', 'Corridor'), ('point_cluster', 'Point Cluster')], max_length=50)),
                ('geojson', models.JSONField(blank=True, help_text='Full GeoJSON polygon/multipolygon', null=True)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bbox_north', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_south', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_east', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_west', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perimeter_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation_min_m', models.IntegerField(blank=True, null=True)),
                ('elevation_max_m', models.IntegerField(blank=True, null=True)),
                ('main_gate_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_gate_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_gate_name', models.CharField(blank=True, max_length=200)),
                ('entry_points', models.JSONField(blank=True, help_text='List of {name, lat, lng, type}', null=True)),
                ('zones', models.JSONField(blank=True, help_text='[{name, description, geojson}]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attraction Boundaries',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('citation_type', models.CharField(choices=[('research_paper', 'Research Paper'), ('book', 'Book'), ('government_report', 'Government Report'), ('news', 'News Article'), ('website', 'Website'), ('ngo_report', 'NGO Report'), ('documentary', 'Documentary')], max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('accessed_date', models.DateField(blank=True, null=True)),
                ('formatted_citation', models.TextField(blank=True, help_text='Auto-generated APA format')),
                ('is_primary_source', models.BooleanField(default=False)),
                ('trust_score', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EndemicSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('conservation_status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], default='LC', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Endemic Species',
                'ordering': ['common_name'],
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='attraction',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attraction',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='attraction',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Hide from search engines'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='og_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
