# Generated by Django 4.2.28 on 2026-03-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_canonical_url_region_meta_description_and_more'),
        ('attractions', '0002_attractionboundary_citation_endemicspecies_and_more'),
        ('blog', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='og_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='schema_json',
            field=models.JSONField(blank=True, help_text='Full JSON-LD structured data', null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='schema_type',
            field=models.CharField(blank=True, choices=[('TouristAttraction', 'Tourist Attraction'), ('Article', 'Article'), ('Person', 'Person'), ('Organization', 'Organization')], max_length=50),
        ),
        migrations.AddField(
            model_name='attraction',
            name='sitemap_changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='attraction',
            name='sitemap_priority',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='endemicspecies',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endemic_species', to='attractions.attraction'),
        ),
        migrations.AddField(
            model_name='citation',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='citations', to='blog.article'),
        ),
        migrations.AddField(
            model_name='citation',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='citations', to='attractions.attraction'),
        ),
        migrations.AddField(
            model_name='citation',
            name='endemic_species',
            field=models.ManyToManyField(blank=True, related_name='citations', to='attractions.endemicspecies'),
        ),
        migrations.AddField(
            model_name='citation',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='citations', to='regions.region'),
        ),
        migrations.AddField(
            model_name='attractionboundary',
            name='attraction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boundary', to='attractions.attraction'),
        ),
    ]
