# Generated by Django 4.2.28 on 2026-03-01 20:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('attractions', '0002_attractionboundary_citation_endemicspecies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='For anonymous users', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='For follow-up', max_length=254)),
                ('feedback_type', models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('correction', 'Correction'), ('compliment', 'Compliment'), ('report_error', 'Report Error'), ('partnership_inquiry', 'Partnership Inquiry'), ('operator_inquiry', 'Operator Inquiry'), ('media_submission', 'Media Submission'), ('general', 'General')], default='general', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating if applicable', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot/photo', max_length=255, null=True, verbose_name='attachment')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, help_text='Public response shown to user')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Review headline', max_length=255)),
                ('body', models.TextField(help_text='Full review text')),
                ('rating', models.IntegerField(help_text='Overall rating 1-5')),
                ('rating_scenery', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('rating_accessibility', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('rating_value_for_money', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('rating_safety', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('rating_facilities', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('visited_at', models.DateField(blank=True, help_text='When they visited', null=True)),
                ('visit_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('group', 'Group'), ('business', 'Business')], max_length=50)),
                ('visit_season', models.CharField(blank=True, choices=[('dry', 'Dry Season'), ('long_rains', 'Long Rains'), ('short_rains', 'Short Rains')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False, help_text='Reported by users')),
                ('helpful_count', models.IntegerField(default=0, help_text='Upvotes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='attractions.attraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
