"""
Django settings for cofig project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-anhs7vhe#q35b4r2pg5zma4btgai+t@eem8vv4_7)*5$am+8_z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition
DEFAULT_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # Add third-party apps here (e.g., 'rest_framework', 'corsheaders', etc.)
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    'drf_spectacular',
]
CUSTOM_APPS = [
    # Add your custom apps here (e.g., 'myapp', etc.)
    "app.accounts",
    "app.attractions",
    "app.regions",
    "app.weather",
    "app.operators",
    "app.partners",
    "app.blog",
    "app.media",
    "app.contributors",
    "app.feedback",
    "app.itinerary",
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',       # must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',    # must be after CommonMiddleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'cofig.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'public'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cofig.wsgi.application'


# Database — SQLCipher encrypted SQLite (default for all environments)
# Overridden to PostgreSQL when DATABASE_URL is set (future cloud upgrade)
DB_ENCRYPTION_KEY = config('DB_ENCRYPTION_KEY', default='')

DATABASES = {
    'default': {
        'ENGINE': 'app.core.db_backends.sqlcipher',
        'NAME': BASE_DIR / 'chui.db',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Dar_es_Salaam'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=config('JWT_REFRESH_TOKEN_LIFETIME', default=1440, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Configuration
_FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
CORS_ALLOWED_ORIGINS = list(filter(None, [
    _FRONTEND_URL,
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]))

CORS_ALLOW_CREDENTIALS = True

# Cache — file-based (multi-process safe, survives restarts, works on PA free tier)
# LocMemCache is per-process; FileBasedCache is shared across all WSGI workers.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/xenohuru-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 3,   # cull 1/3 of entries when MAX_ENTRIES hit
        }
    }
}

# Full-page cache timeout for anonymous GET requests (via cache middleware)
CACHE_MIDDLEWARE_SECONDS = 60          # 1 minute for list/public endpoints
CACHE_MIDDLEWARE_KEY_PREFIX = 'xeno'

# Weather API Configuration
WEATHER_API_BASE_URL = 'https://api.open-meteo.com/v1/forecast'
WEATHER_CACHE_TIMEOUT = 1800  # 30 minutes

# OpenAPI / Swagger UI Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Xenohuru API',
    'DESCRIPTION': 'API for Tanzania Tourism platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Xenohuru API <noreply@xenohuru.com>')
CONTACT_EMAIL = config('CONTACT_EMAIL', default='')  # Your personal email for notifications

# Render.com production overrides
# Activates when RENDER=True is set in environment variables
if config('RENDER', default=False, cast=bool):
    DEBUG = False
    RENDER_EXTERNAL_URL = config('RENDER_EXTERNAL_URL', default='')
    ALLOWED_HOSTS = list(filter(None, [
        config('RENDER_EXTERNAL_HOSTNAME', default=''),
        'localhost',
        '127.0.0.1',
    ]))
    CORS_ALLOWED_ORIGINS = list(filter(None, [
        config('FRONTEND_URL', default=''),
        RENDER_EXTERNAL_URL,
    ]))
    # SQLCipher backend handles all WAL/perf PRAGMAs automatically

# These activate when ON_PYTHONANYWHERE=True is set in the server .env
if config('ON_PYTHONANYWHERE', default=False, cast=bool):
    DEBUG = False
    PA_USERNAME = config('PYTHONANYWHERE_USERNAME', default='xenohuru')
    ALLOWED_HOSTS = [
        f'{PA_USERNAME}.pythonanywhere.com',
        'localhost',
        '127.0.0.1',
    ]
    CORS_ALLOWED_ORIGINS = list(filter(None, [
        config('FRONTEND_URL', default=''),
        f'https://{PA_USERNAME}.pythonanywhere.com',
    ]))
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = Path(f'/home/{PA_USERNAME}/main/media')
    DATABASES['default']['NAME'] = Path(f'/home/{PA_USERNAME}/main/chui.db')

    # Tighter cache on PA: use /home dir so it persists across reloads
    CACHES['default']['LOCATION'] = f'/home/{PA_USERNAME}/main/.cache'

