# Generated by Django 4.2.28 on 2026-03-01 20:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0002_attractionboundary_citation_endemicspecies_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('schema_type', models.CharField(blank=True, choices=[('TouristAttraction', 'Tourist Attraction'), ('Article', 'Article'), ('Person', 'Person'), ('Organization', 'Organization')], max_length=50)),
                ('schema_json', models.JSONField(blank=True, help_text='Full JSON-LD structured data', null=True)),
                ('no_index', models.BooleanField(default=False, help_text='Hide from search engines')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tier', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-Range'), ('luxury', 'Luxury')], default='mid', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attractions', models.ManyToManyField(blank=True, help_text='Attractions this operator covers', related_name='operators', to='attractions.attraction')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
            ],
            options={
                'ordering': ['-is_verified', 'name'],
                'indexes': [models.Index(fields=['tier'], name='operators_t_tier_0308ed_idx'), models.Index(fields=['is_verified'], name='operators_t_is_veri_d68ba1_idx')],
            },
        ),
    ]
